### ISSUE TITLE
document.execCommand("paste") won't pick up new changes after an image enters the clipboard

### ISSUE THREAD

**Issue by kanjieater** [Onurtag/clipboard-inserter#3]
I've been using your clipboard inserter for a while now and it's been working great. Textractor always works fine. I've ran into a strange issue that seems reproducible by others for the Fate Stay Night patch that allows copying directly to the clipboard (since it's not hookable anymore). 

I'm on Windows 11. Chrome 112.0.5615.86

1. Install the Fate Realta Nua patch, it's in the _usual_ places pre-patched and then you can apply the latest 1.14 patch over it. Contact me on discord if you need help. `KanjiEater#4646`
https://forums.nrvnqsr.com/showthread.php/9101-Fate-Stay-Night-Realta-Nua-Ultimate-Edition-2022
2. Mark the setting in tools to allow for automatic clipboard copying
3. At this point the game should be copying text just fine in your texthooker of choice (renji's texthooker-ui is mine, but any should reproduce)
4. Take a screenshot that copies an image to clipboard with something like Sharex
5. `document.execCommand("paste");` no longer reads from the clipboard. I can paste the new lines from the game directly into the texthooker, but the browser's paste command no longer reads the text data after the image data exists in the clipboard.
6. Restarting seems to fix it until you take a screenshot again.

Note that this flow works fine for other games with textractor, so I'm very confused on what would cause this. Also note the new navigator api reads the data in just fine, so this seems to be an issue with old clipboard reading method.

I'm working around this by using this small python script
https://github.com/kanjieater/clipboard_to_websocket

**Comment by Onurtag** [comment]
I have pushed an update for the Chrome branch in an attempt to fix this issue. 
Can you update and test the new version on your end to see if the bug is still happening? 
Let me know.

Also that python script looks great. Thanks for sharing.

**Comment by kanjieater** [comment]
This doesn't seem to fix the issue. Looking at the source, I wouldn't expect it to to as the issue is the document.execCommand("paste"); stops reading new data from the clipboard after an image is inserted in this one very weird case. I'm not sure if it's how the clipboard is being encoded, a chrome bug or what, but it is reproducible.

**Comment by Onurtag** [comment]
I see. That does indeed sound similar to a chromium-only bug that I have also encountered while using foobar2000. 
Like you said the `document.execCommand("paste")` method sometimes straight-up doesn't work. This mostly happens when it encounters some weird clipboard formats.
Sadly there is still no other way to get clipboard content on chromium unintrusively.  

For now using an external script like the one you shared above is probably the cleanest solution.
