### ISSUE TITLE
Firefox doesn't work for "Detect url containing" feature

### ISSUE THREAD

**Issue by kanjieater** [Onurtag/clipboard-inserter#4]
Due to the other issue I posted #3 I tried Firefox, which doesn't have the same issue, but won't allow the clipboard inserter ext to turn on automatically.
![image](https://user-images.githubusercontent.com/32607317/232475542-46d47acc-c402-4893-9620-2cb08e636e0d.png)

I refresh the page and you can see the ext is turned off:
![image](https://user-images.githubusercontent.com/32607317/232475666-4e5f72e2-de38-4ff2-81fd-b4b4d4364235.png)

**Comment by Onurtag** [comment]
First of all thanks for the bug reports.  

There were some severe bugs with the `Detect url containing` function on Firefox. I have pushed an update and released a new version for Firefox. This bug should hopefully be fixed now.   
Please confirm and let me know if there are any more problems.

**Comment by kanjieater** [comment]
It does fix the firefox issue, but it created another bug. I was testing out firefox, but it's unusable with yomichan for me, so I went back to chrome, where my url looks like this:

![image](https://user-images.githubusercontent.com/32607317/232631580-0f431133-3862-43e0-84fc-26a23adb1180.png)


if I left it as texthooker-ui it would turn on automatically for the github page for the that texthooker too which isn't something I wanted. So continuing to allow for the `/`'s would be nice.

**Comment by Onurtag** [comment]
On both browsers with the latest update the extension just checks if the url contains the given string so it should correctly match a string that contains slashes like the one above.  

Although I had to push another update as some url-unsafe characters (like spaces) weren't matching correctly. Now it encodes the given string with encodeURI() before checking if the url includes it. 
If the new version still doesn't work for your case let me know.
