### ISSUE TITLE
`<pre>` element not preserving line breaks

### ISSUE THREAD

**Issue by harrisonmg** [Onurtag/clipboard-inserter#5]
I'd like to preserve line breaks so that Yomitan can correctly detect the full sentence for Anki card generation.

Following the tooltip suggestion, I chose the `pre` element, but line breaks are still not present, as you can see in the screenshot below:

![image](https://github.com/Onurtag/clipboard-inserter/assets/3968357/b2c2c4a8-6b91-4783-9357-3379e885cb83)

**Comment by Onurtag** [comment]
Testing the same situation on the same website with the following settings:
![image](https://github.com/Onurtag/clipboard-inserter/assets/7430003/1f3bdc1d-768b-4684-ae80-95b3ceb19a21)
It works on my side as you can see in the below image:
![image](https://github.com/Onurtag/clipboard-inserter/assets/7430003/940f772f-b744-475f-9d13-3c1551ac1127)

The problem might be that your texthooker isn't detecting the newlines correctly. Try testing the situation by copying a multiline text manually.

---

**Although;** 
That website doesn't look like it can handle `pre` lines (looks like the counter isn't updating).   
You should instead use the default `p` tag and use an css injecting extension such as Stylus to allow `p` tags to show newlines. Just add a new style for the page and use the following css code:

```css
p {
  white-space: pre;
}
```

**Comment by harrisonmg** [comment]
Ok, I think I understand a bit better - some more testing confirms my understanding. Thanks for the help!
